//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data.Responsity
{
    using System;
    using System.Collections.Generic;
    
    public partial class M_Master_Data
    {
        public int ID { get; set; }
        public string Name { get; set; }
        public string Values { get; set; }
    }
}
