//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data.Responsity
{
    using System;
    using System.Collections.Generic;
    
    public partial class M_News
    {
        public int ID_News { get; set; }
        public string Title { get; set; }
        public string Detail { get; set; }
        public System.DateTime CreateDt { get; set; }
        public Nullable<System.DateTime> UpdateDt { get; set; }
    }
}
