//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data.Responsity
{
    using System;
    using System.Collections.Generic;
    
    public partial class M_Product
    {
        public int ID_Product { get; set; }
        public string Image { get; set; }
        public string Size { get; set; }
        public int Total { get; set; }
        public System.DateTime CreateDt { get; set; }
        public int CreateBy { get; set; }
        public Nullable<System.DateTime> UpdateDt { get; set; }
        public Nullable<int> UpdateBy { get; set; }
        public string Status { get; set; }
    }
}
