//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data.Responsity
{
    using System;
    using System.Collections.Generic;
    
    public partial class M_User_Login
    {
        public int ID { get; set; }
        public string Email { get; set; }
        public string Password { get; set; }
        public string User_Role { get; set; }
        public Nullable<System.DateTime> Recent_login { get; set; }
    }
}
